[workspace]
members = ["gpu-protocol", "kernel", "userland", "xtask"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["RustOS contributors"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
debug = 1
