[package]
name = "rustos-xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ed25519-dalek = { version = "3.0.0", default-features = false, features = ["signature"] }
rustos-gpu-protocol = { path = "../gpu-protocol" }
sha2 = { version = "0.11.0", default-features = false }
bootloader = "=0.11.17"
fatfs = { version = "=0.3.6", default-features = false, features = ["std", "alloc"] }
gpt = "=3.1.0"
